
from yacs.config import CfgNode as CN

_C = CN()

_C.SEED = 0

_C.MODEL = CN()
_C.MODEL.MODEL_NAME = ''
_C.MODEL.CHECKPOINT = ''
_C.MODEL.INFERENCE = CN()
_C.MODEL.INFERENCE.ENABLE = False
_C.MODEL.INFERENCE.CKT_IGNORE_LIST = ['his_decoder']
_C.MODEL.FEATURE_HEAD = CN()
_C.MODEL.FEATURE_HEAD.LINEAR_ENABLED = True
_C.MODEL.FEATURE_HEAD.LINEAR_OUT_FEATURES = 1024
_C.MODEL.FEATURE_HEAD.LINEAR_OUT_FEATURES_LONG = 256

_C.MODEL.LSTR = CN()
_C.MODEL.LSTR.NUM_HEADS = 8
_C.MODEL.LSTR.DIM_FEEDFORWARD = 1024
_C.MODEL.LSTR.DIM_FEEDFORWARD_LONG = 256
_C.MODEL.LSTR.DROPOUT = 0.2
_C.MODEL.LSTR.ACTIVATION = 'relu'
_C.MODEL.LSTR.AGES_MEMORY_SECONDS = 0
_C.MODEL.LSTR.AGES_MEMORY_SAMPLE_RATE = 1
_C.MODEL.LSTR.LONG_MEMORY_SECONDS = 0
_C.MODEL.LSTR.LONG_MEMORY_SAMPLE_RATE = 1
_C.MODEL.LSTR.WORK_MEMORY_SECONDS = 0.25
_C.MODEL.LSTR.WORK_MEMORY_SAMPLE_RATE = 1
_C.MODEL.LSTR.ENC_MODULE = [
    [16, 1, True], [32, 2, True]
]
_C.MODEL.LSTR.DEC_MODULE = [-1, 2, True]


_C.MODEL.LSTR.INFERENCE_MODE = 'batch'

_C.MODEL.LSTR.HISTORY = CN()
_C.MODEL.LSTR.HISTORY.SEQ_COMPRESSION = CN()
_C.MODEL.LSTR.HISTORY.SEQ_COMPRESSION.ENC = [16, 1, True]
_C.MODEL.LSTR.HISTORY.SEQ_COMPRESSION.DIM = 256
_C.MODEL.LSTR.HISTORY.SEQ_COMPRESSION.FEEDFORWARD = 256
_C.MODEL.LSTR.HISTORY.SEQ_COMPRESSION.NUM_HEADS = 8

_C.MODEL.LSTR.HISTORY.PROCESS = CN()
_C.MODEL.LSTR.HISTORY.PROCESS.ENC = [-1, 3, True]
_C.MODEL.LSTR.HISTORY.PROCESS.QKV = [1024, 1024, 1024]

_C.MODEL.LSTR.HISTORY.DIMRES = CN()
_C.MODEL.LSTR.HISTORY.DIMRES.ENC = [8, 1, True]
_C.MODEL.LSTR.HISTORY.DIMRES.DIM = 512
_C.MODEL.LSTR.HISTORY.DIMRES.FEEDFORWARD = 512
_C.MODEL.LSTR.HISTORY.DIMRES.NUM_HEADS = 8
_C.MODEL.LSTR.HISTORY.DIMRES.QKV = [512, 256, 256]
_C.MODEL.LSTR.HISTORY.WINDOW = CN()

_C.MODEL.LSTR.HISTORY.WINDOW.SIZE = 32
_C.MODEL.LSTR.HISTORY.WINDOW.DIM = 256
_C.MODEL.LSTR.HISTORY.WINDOW.NUM_HEADS = 8

_C.MODEL.LSTR.HISTORY.WINDOW.ACTIVATION = 'relu'
_C.MODEL.LSTR.HISTORY.WINDOW.QKV = [256, 256, 256]

_C.MODEL.SWIN = CN() 
_C.MODEL.SWIN.NUM_HEADS = [4, 4] 
_C.MODEL.SWIN.WINDOW_SIZE = [32, 8]
_C.MODEL.SWIN.OUT_SIZE = [8, 2]

_C.MODEL.SWIN.MLP_RATIO = 4. 
_C.MODEL.SWIN.QKV_BIAS = True 
_C.MODEL.SWIN.QK_SCALE = None
_C.MODEL.SWIN.DROP_PATH_RATE = 0.1
_C.MODEL.SWIN.DROP_PATH_START = 0.05
_C.MODEL.SWIN.PATCH_NORM = True 
_C.MODEL.SWIN.GLOBAL = True 

_C.MODEL.SWIN.TSM = CN()
_C.MODEL.SWIN.TSM.INPUT_DIM = [256,512]
_C.MODEL.SWIN.TSM.HIDDEN_DIM = [128, 256]
_C.MODEL.SWIN.TSM.DROPOUT = 0.1
_C.MODEL.SWIN.TSM.ATTN_DROPOUT = 0.1
_C.MODEL.SWIN.TSM.OUT_DROPOUT = 0.1

_C.MODEL.GASSION = CN()
_C.MODEL.GASSION.POS_RANGE = 1.
_C.MODEL.GASSION.MIU = 0.
_C.MODEL.GASSION.SIG = 1. 
_C.MODEL.GASSION.NORMALIZE = True
_C.MODEL.GASSION.WEIGHT = 0.5

_C.MODEL.CRITERIONS = [['MCE', {}]]

_C.DATA = CN()

_C.DATA.DATA_NAME = None
_C.DATA.DATA_ROOT = None
_C.DATA.CLASS_NAMES = None
_C.DATA.NUM_CLASSES = None
_C.DATA.IGNORE_INDEX = None
_C.DATA.METRICS = None
_C.DATA.FPS = None
_C.DATA.TRAIN_SESSION_SET = None
_C.DATA.TEST_SESSION_SET = None

_C.DATA.MOVE_STEP = 1 


_C.DATA.AUG = CN()
_C.DATA.AUG.ENABLE = False
_C.DATA.AUG.TYPE = 'random drop'
_C.DATA.AUG.RANDOM_DROP_RATE = 0.1

_C.DATA.AUG.FIRST_DROP_RATE = 0.1 

_C.INPUT = CN()
_C.INPUT.MODALITY = 'twostream'
_C.INPUT.VISUAL_FEATURE = 'rgb_anet_resnet50'
_C.INPUT.MOTION_FEATURE = 'flow_anet_resnet50'
_C.INPUT.TARGET_PERFRAME = 'target_perframe'

_C.DATA_LOADER = CN()
_C.DATA_LOADER.BATCH_SIZE = 32
_C.DATA_LOADER.NUM_WORKERS = 4
_C.DATA_LOADER.PIN_MEMORY = False

_C.SOLVER = CN()
_C.SOLVER.START_EPOCH = 1
_C.SOLVER.NUM_EPOCHS = 50

_C.SOLVER.OPTIMIZER = 'adam'
_C.SOLVER.BASE_LR = 0.00005
_C.SOLVER.WEIGHT_DECAY = 0.00005
_C.SOLVER.MOMENTUM = 0.9

_C.SOLVER.SCHEDULER = CN()
_C.SOLVER.SCHEDULER.SCHEDULER_NAME = 'multistep'
_C.SOLVER.SCHEDULER.MILESTONES = []
_C.SOLVER.SCHEDULER.GAMMA = 0.1
_C.SOLVER.SCHEDULER.WARMUP_FACTOR = 0.3
_C.SOLVER.SCHEDULER.WARMUP_EPOCHS = 10.0
_C.SOLVER.SCHEDULER.WARMUP_METHOD = 'linear'

_C.SOLVER.PHASES = ['train', 'test']

_C.OUTPUT_DIR = 'checkpoints'
_C.SESSION = ''

_C.VERBOSE = False

_C.AIM = CN()
_C.AIM.ENABLE = False
_C.AIM.EXPERIMENT_NAME = 'debug'
_C.AIM.RUN_NAME = 'downsample'
_C.OAS = CN()
_C.OAS.ENABLE=False
_C.OAS.EMB_DIM=[1024, 1024, 1024, 1024]
_C.OAS.NUM_LAYERS = [4, 8, 4, 2] 
_C.OAS.NUM_HEADS = [16,16,16,16]
_C.OAS.TSM_DROPOUT = 0.1 

_C.OAS.LOCAL = CN()
_C.OAS.LOCAL.ENABLE = False
_C.OAS.SCUT = CN()
_C.OAS.SCUT.ENABLE = False
_C.OAS.SCUT.DENSE = CN()

_C.OAS.SCUT.DENSE.EMB_DIM = 1024


_C.CASCADE = CN()
_C.CASCADE.ENABLE = False
_C.CASCADE.TYPE='SA'

_C.CASCADE.OAS_ENBALE=False
_C.CASCADE.OAS_SHARED=True

_C.CASCADE.SA = CN()
_C.CASCADE.SA.NUM_STAGES = 2
_C.CASCADE.SA.NUM_LAYERS = [2] 
_C.CASCADE.SA.HIDDEN_DIM = 128 
_C.CASCADE.SA.NUM_CLASSES = 22
_C.CASCADE.SA.NUM_HEADS = [2]
_C.CASCADE.SA.DROPOUT = 0.1
_C.CASCADE.SA.ACTIVATION = 'relu'
_C.CASCADE.SA.NORM = False
_C.CASCADE.SA.SHORTCUT = True

_C.DDP = CN()
_C.DDP.ENABLE=False
_C.DDP.SYNC_BN=False

def get_cfg():
    return _C.clone()